name: ecoruta_cafetera
description: Sistema territorial de censo cafetero para Santander - EcoRuta Cafetera
publish_to: 'none'
version: 2.4.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Navigation
  go_router: ^14.6.1
  
  # State management
  flutter_riverpod: ^2.6.1
  
  # Icons & Fonts
  google_fonts: ^6.2.1
  
  # Connectivity
  connectivity_plus: ^6.1.1

  # Animations
  flutter_animate: ^4.5.0

  # Maps
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  # Location
  geolocator: ^13.0.2

  # HTTP
  http: ^1.2.0

  # Session persistence
  shared_preferences: ^2.3.0

  # PDF generation
  pdf: ^3.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#1A3D1A"
  adaptive_icon_foreground: "assets/icon/app_icon_fg.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
